### ISSUE TITLE
In events page try replacing the whole screen in a single swap.

### ISSUE THREAD

**Issue by DEVAbhinav** [ncs-jss/hackncs-17#11]
while opening the events page 2 poster comes up then in a single swap instead of partial scrolling see if the whole of screen could be replaced with new posters.

**Comment by itaditya** [comment]
On it Sir

**Comment by itaditya** [comment]
As I mentioned the issue in the commit , it got closed automatically, but it would be reat if @DEVAbhinav Sir , you can review and then instruct accordingly
