### ISSUE TITLE
Navigation in club page.

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/hackncs-17#13]
There is now way to get back to the cub page after clicking on one of the clubs without having to go back to the home page. Please rectify this.

**Comment by itaditya** [comment]
I have fixed this in f776d21f46937c8722a638c4d160e465a697b52c

**Comment by DEVAbhinav** [comment]
This issue is fixed but animation to get back is a bit long try reducing the time period between clicking the cross sign and re-appearing of club page.

**Comment by abhayraw1** [comment]
@itaditya reduce the animation time and the close this issue.

**Comment by itaditya** [comment]
Ok Sir
