### ISSUE TITLE
The next up section.

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/hackncs-17#14]
Provide the necessary registration link for the particular event in the next up part of the home page.

**Comment by yashvardhan12** [comment]
ok sir

**Comment by DEVAbhinav** [comment]
This link is redirecting to fb page instead it should redirect to register page

**Comment by itaditya** [comment]
Ok

**Comment by abhayraw1** [comment]
@DEVAbhinav the link will be changed from the backend itself so that's not an issue.
