### ISSUE TITLE
Navigating to the top of every page.

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/hackncs-17#16]
Provide the go to top button on all pages having scroll functionality.

**Comment by abhayraw1** [comment]
Just a suggestion..
You could split the down arrow button into two buttons as soon as the user scrolls the page.

**Comment by itaditya** [comment]
Sir , if the user is at the bottom page and he continues to scroll down then he gets to the top . So do we still need the arrow

**Comment by abhayraw1** [comment]
I don't think that's a good idea. 
@sidjain2901  @DEVAbhinav care to comment?
Whenever the user reaches then end of the page and scrolls further, you should indicate it rather hen sending him to the top. Looks like bad UX to me.

**Comment by DEVAbhinav** [comment]
Yes sir this issue is currently fixed in home and events page.

**Comment by DEVAbhinav** [comment]
Looping in page scroll will be definitely removed.

**Comment by itaditya** [comment]
The events page now have a scroll to top feature and there is no looping , shall I close this @abhayraw1  ?

**Comment by DEVAbhinav** [comment]
Things seems good! I am closing this issue @abhayraw1  sir.
