### ISSUE TITLE
Scrolling issue in events page

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/hackncs-17#17]
After clicking on an event the pop up (or whatever...) doesn't scroll.
On scrolling the background appears to be scrolling instead of the popup.

**Comment by DEVAbhinav** [comment]
@itaditya  see if the popup really needs a vertical scrollbar because its a poster of fixed dimensions.

**Comment by itaditya** [comment]
Actually Sir ,the poster was a little reduntant in the modal , so I think we should not show it in the modal .

The other work around is that I keep the height of poster fixed and width be automatic , If you are free , I can come and show you that now. and also integrate backend , 

And what you mentioned is not the case as we will have different images for different events of different sizes

**Comment by itaditya** [comment]
It seems this is an issue with the one page scroll plugin itself (https://github.com/peachananr/onepage-scroll/issues/229) , I tried every viable option but there is only one workaround which is to prevent the popup from overflowing (thereby no need for scroll) ,

**Comment by DEVAbhinav** [comment]
This looks good now !! More suggestion from @sidjain2901  sir expected!
