### ISSUE TITLE
Connect with us.

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/hackncs-17#19]
Provide the official mail id of nibble along with the link for the facebook page.
You can also add them at the bottom of the main page itself.

**Comment by itaditya** [comment]
Ok Sir

**Comment by DEVAbhinav** [comment]
Issue is fixed but @yashvardhan12  see if you could make it more sober

**Comment by yashvardhan12** [comment]
okay sir, will look into it.

**Comment by abhayraw1** [comment]
Maybe you could use icons...

**Comment by yashvardhan12** [comment]
sure sir!

**Comment by DEVAbhinav** [comment]
Great job!
