### ISSUE TITLE
Integration of apis

### ISSUE THREAD

**Issue by DEVAbhinav** [ncs-jss/hackncs-17#21]
1.)get :  /getEvents  // gives you list of all the Events.

2.)post : /studentRegister // accepting  an object  {email : **,number: ** , year :  ** , name: ** ,admissionNumber : **,event_id: **};

 are ready  for use.

**Comment by itaditya** [comment]
Sir please fix issue #8  so that I can run the server .

**Comment by DEVAbhinav** [comment]
I have already posted the solution for  #8  issue

**Comment by DEVAbhinav** [comment]
@itaditya  I have allowed cors you can continue integration.

**Comment by itaditya** [comment]
@DEVAbhinav , the CORS issue is still there , see #24 .

**Comment by itaditya** [comment]
Now , only the APIs regarding student registration is left , will do it ASAp

**Comment by itaditya** [comment]
All APIs are integrated , please review them .

**Comment by DEVAbhinav** [comment]
Great Job!!
