### ISSUE TITLE
Fix CORS .

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/hackncs-17#24]
@DEVAbhinav , I checked the ajax requests and they are still not working , please look into it .
The console error is -
 XMLHttpRequest cannot load http://techtrek.hackncs.com/api/upcomingEvent. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access.

Have you pushed your fixed code onto our test server ?

**Comment by DEVAbhinav** [comment]
CHeck now ! @itaditya

**Comment by itaditya** [comment]
Its Working Now , great
