### ISSUE TITLE
Arrow in home page

### ISSUE THREAD

**Issue by DEVAbhinav** [ncs-jss/hackncs-17#26]
After coming to bottom there should be an arrow taking user back to top. Implement the feature discussed yesterday.

**Comment by DEVAbhinav** [comment]
Or can we use a new arrow at the footer itself??

**Comment by itaditya** [comment]
Nice Idea Sir

**Comment by itaditya** [comment]
Fixed this issue ,please review it

**Comment by DEVAbhinav** [comment]
Seems good now!
