### ISSUE TITLE
Event_page not updated

### ISSUE THREAD

**Issue by kunalvishnoi** [ncs-jss/hackncs-17#30]
Event page still shows the old poster of 2016..

**Comment by itaditya** [comment]
Ok if you would like to contribute you can collect the poster images of all the latest events from Fb in portait and lanscape. After that we can easily add them to the page.

**Comment by ohiofi** [comment]
Grabbed lots of posters from the [NCS Facebook page](facebook.com/pg/nibblecomputersociety/photos/) and put them in a new folder public/media/fb_posters

I submitted a pull request [here](https://github.com/ncs-jss/hackncs-17/pull/31)

**Comment by itaditya** [comment]
@20hz20khz, you have added lots of really old posters which we don't need to add. Please add only the posters which are posted in 2016-17
