### ISSUE TITLE
config.js file is absent

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/hackncs-17#8]
![image](https://cloud.githubusercontent.com/assets/15871340/22286825/74835bb6-e316-11e6-997f-35554772347b.png)

The console shows error at line 3 of server.js , because config.js is not present but is referenced there. 
Please fix it .

**Comment by DEVAbhinav** [comment]
Try by creating an empty config file in your local system.

**Comment by DEVAbhinav** [comment]
Its already mentioned in the git ignore.

**Comment by itaditya** [comment]
Still not working 
![image](https://cloud.githubusercontent.com/assets/15871340/22307599/a8d3c042-e369-11e6-8fcc-5f812ae9d4ad.png) 

After I removed `()` after require , it shows new error related to sequelise , 
![image](https://cloud.githubusercontent.com/assets/15871340/22307633/cbb57f88-e369-11e6-92a8-186d05c4b3ff.png)

**Comment by DEVAbhinav** [comment]
Try coping this in dbConfig file
`module.exports= function() {
return {
		dbName : '****', //a local database name
		dbUserName : '****', //your mysql username @ local machine 
		dbPassword : '*****',  //your mysql password @local machine
		host : 'localhost' 
	}
}
Tell me if this works

**Comment by DEVAbhinav** [comment]
Have your tried the solution mentioned in above comment? @itaditya

**Comment by itaditya** [comment]
Got this error
https://cloud.githubusercontent.com/assets/15871340/22307633/cbb57f88-e369-11e6-92a8-186d05c4b3ff.png

**Comment by DEVAbhinav** [comment]
I think this issue should be closed
